--CREATE DATABASE NORTHWIND;

--USE NORTHWIND;

CREATE TABLE REGIONS(
	REGION_ID INT PRIMARY KEY,
	DESCRIPTION VARCHAR(15)
);

CREATE TABLE CATEGORIES(
	CATEGORY_ID INT PRIMARY KEY,
	CATEGORY_NAME VARCHAR(30),
	DESCRIPTION VARCHAR(100)
);

CREATE TABLE TERRITORIES(
	TERRITORY_ID INT PRIMARY KEY,
	TERRITORY_DESCRIPTION VARCHAR(30),
	REGION_ID INT
	CONSTRAINT fk_region_id FOREIGN KEY (REGION_ID)
	REFERENCES REGIONS(REGION_ID)
);

CREATE TABLE SHIPPERS(
	SHIPPER_ID INT PRIMARY KEY,
	COMPANY_NAME VARCHAR(20),
	PHONE VARCHAR(15)
);

CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT PRIMARY KEY,
	LAST_NAME VARCHAR(15),
	FIRST_NAME VARCHAR(15),
	TITLE VARCHAR(50),
	TITLE_OF_COURTESY VARCHAR(5),
	BIRTH_DATE DATE,
	HIRE_DATE DATE,
	ADDRESS VARCHAR(40),
	CITY VARCHAR(20),
	REGION VARCHAR(30),
	POSTAL_CODE VARCHAR(20),
	COUNTRY VARCHAR(10),
	HOME_PHONE VARCHAR(20),
	EXTENSION VARCHAR(20),
	REPORTS_TO INT

	CONSTRAINT fk_emp_reports_to FOREIGN KEY(REPORTS_TO)
	REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE EMPLOYEE_TERRITORIES(
	EMPLOYEE_ID INT,
	TERRITORY_ID INT
	
	CONSTRAINT fk_emp_territory FOREIGN KEY(EMPLOYEE_ID)
	REFERENCES EMPLOYEES(EMPLOYEE_ID),
	CONSTRAINT fk_territory FOREIGN KEY(TERRITORY_ID)
	REFERENCES TERRITORIES(TERRITORY_ID)
);

CREATE TABLE CUSTOMERS(
	CUSTOMER_ID VARCHAR(10) PRIMARY KEY,
	COMPANY_NAME VARCHAR(50),
	CONTACT_NAME VARCHAR(30),
	CONTACT_TITLE VARCHAR(30),
	ADDRESS VARCHAR(30),
	CITY VARCHAR(30),
	REGION VARCHAR(30),
	POSTAL_CODE VARCHAR(30),
	COUNTRY VARCHAR(30),
	PHONE VARCHAR(30),
	FAX VARCHAR(30)
);

CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
	CUSTOMER_ID Varchar(10),
	EMPLOYEE_ID INT,
	ORDER_DATE DATE,
	REQUIRE_DATE DATE,
	SHIPPED_DATE DATE,
	SHIP_VIA INT,
	FRIGHT DECIMAL(6,2),
	SHIP_NAME VARCHAR(50),
	SHIP_ADDRESS VARCHAR(80),
	SHIP_CITY VARCHAR(30),
	SHIP_REGION VARCHAR(30),
	SHIP_POSTAL_CODE VARCHAR(50),
	SHIP_COUNTRY VARCHAR(30)

	CONSTRAINT fk_order_cust FOREIGN KEY(CUSTOMER_ID)
	REFERENCES CUSTOMERS(CUSTOMER_ID),
	CONSTRAINT fk_order_emp FOREIGN KEY(EMPLOYEE_ID)
	REFERENCES EMPLOYEES(EMPLOYEE_ID),
	CONSTRAINT fk_order_shippers FOREIGN KEY(SHIP_VIA)
	REFERENCES SHIPPERS(SHIPPER_ID)
);

CREATE TABLE SUPPLIERS(
	SUPPLIER_ID INT PRIMARY KEY,
	COMPANY_NAME VARCHAR(50),
	CONTACT_NAME VARCHAR(30),
	CONTACT_TITLE VARCHAR(30),
	ADDRESS VARCHAR(80),
	CITY VARCHAR(30),
	REGION VARCHAR(30),
	POSTAL_CODE VARCHAR(20),
	COUNTRY VARCHAR(30),
	PHONE VARCHAR(30),
	FAX VARCHAR(30),
	HOME_PAGE VARCHAR(100)
);

CREATE TABLE PRODUCTS(
	PRODUCT_ID INT PRIMARY KEY,
	PRODUCT_NAME VARCHAR(50),
	SUPPLIER_ID INT,
	CATEGORY_ID INT,
	QUANTITY_PER_UNIT VARCHAR(50),
	UNIT_PRICE DECIMAL(5,2),
	UNITS_IN_STOCK INT,
	UNITS_ON_ORDER INT,
	REORDER_LEVEL INT,
	DISCONTINUED INT

	CONSTRAINT fk_product_supplier FOREIGN KEY(SUPPLIER_ID)
	REFERENCES SUPPLIERS(SUPPLIER_ID),
	CONSTRAINT fk_product_category FOREIGN KEY(CATEGORY_ID)
	REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE ORDER_DETAILS(
	ORDER_ID INT,
	PRODUCT_ID INT,
	QUANTITY INT,
	DISCOUNT DECIMAL(3,2)

	CONSTRAINT fk_or_det_orders FOREIGN KEY (ORDER_ID)
	REFERENCES ORDERS(ORDER_ID),
	CONSTRAINT fk__or_det_products FOREIGN KEY(PRODUCT_ID)
	REFERENCES PRODUCTS(PRODUCT_ID)
);